#!/usr/bin/env bash
# Installs Nginx non-interactively, then starts it and serves a page containing "Holberton School"
export DEBIAN_FRONTEND=noninteractive
export NEEDRESTART_MODE=a
apt-get update -y
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.html
service nginx start
