#!/usr/bin/env bash
# Installs Nginx, starts it without systemctl, and serves a page containing "Holberton School"
apt-get update -y
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx start
service nginx restart
